//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannedWord
    {
        public int id { get; set; }
        public string bannedWord1 { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
