//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannedWord
    {
        public int id { get; set; }
        public string bannedWord1 { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
