//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammedTweet
    {
        public int Id { get; set; }
        public string Tweet { get; set; }
        public System.DateTime Time { get; set; }
        public bool Tweeted { get; set; }
        public string Link { get; set; }
    }
}
