//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammedTweet
    {
        public int Id { get; set; }
        public string Tweet { get; set; }
        public System.DateTime Time { get; set; }
        public bool Tweeted { get; set; }
        public string Link { get; set; }
    }
}
