//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TweetBootyDBEntities : DbContext
    {
        public TweetBootyDBEntities()
            : base("name=TweetBootyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BannedWord> BannedWords { get; set; }
        public DbSet<Hashtag> Hashtags { get; set; }
        public DbSet<Link> Links { get; set; }
        public DbSet<Tweet> Tweets { get; set; }
    }
}
