//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweeted
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Action { get; set; }
        public string Username { get; set; }
        public Nullable<double> TweetId { get; set; }
    }
}
