//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweeted
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Action { get; set; }
        public string Username { get; set; }
        public Nullable<double> TweetId { get; set; }
    }
}
