//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetBooty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TweetBootyDBEntities : DbContext
    {
        public TweetBootyDBEntities()
            : base("name=TweetBootyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BannedWord> BannedWords { get; set; }
        public DbSet<Hashtag> Hashtags { get; set; }
        public DbSet<Link> Links { get; set; }
        public DbSet<Tweet> Tweets { get; set; }
        public DbSet<Tweeted> Tweeteds { get; set; }
    }
}
